headers = {
    "server": "GitHub.com",
    "date": "Mon, 01 Mar 2021 22:30:25 GMT",
    "content-type": "application/json; charset=utf-8",
    "transfer-encoding": "chunked",
    "cache-control": "private, max-age=60, s-maxage=60",
    "vary": "Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With",
    "etag": 'W/"ee6c470b0ecab9bdbca208c69a0e001853de145764cfdd3679a9065a9ee84fdc"',
    "last-modified": "Mon, 01 Mar 2021 16:06:46 GMT",
    "x-oauth-scopes": "read:user, user:email",
    "x-accepted-oauth-scopes": "",
    "x-oauth-client-id": "5ffe8fd42976c5f477e3",
    "x-github-media-type": "github.v3; format=json",
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4991",
    "x-ratelimit-reset": "1614640402",
    "x-ratelimit-used": "9",
    "access-control-expose-headers": (
        "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Us"
        "ed, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Dep"
        "recation, Sunset"
    ),
    "access-control-allow-origin": "*",
    "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
    "x-frame-options": "deny",
    "x-content-type-options": "nosniff",
    "x-xss-protection": "1; mode=block",
    "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
    "content-security-policy": "default-src 'none'",
    "content-encoding": "gzip",
    "x-github-request-id": "25AC:04EB:BE9E1:E3009:603D6B01",
}

user = {
    "login": "sus009",
    "id": 2490805,
    "node_id": "MDQ6VXNlcjI0OTA4MDU=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2490805?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sus009",
    "html_url": "https://github.com/sus009",
    "followers_url": "https://api.github.com/users/sus009/followers",
    "following_url": "https://api.github.com/users/sus009/following{/other_user}",
    "gists_url": "https://api.github.com/users/sus009/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sus009/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sus009/subscriptions",
    "organizations_url": "https://api.github.com/users/sus009/orgs",
    "repos_url": "https://api.github.com/users/sus009/repos",
    "events_url": "https://api.github.com/users/sus009/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sus009/received_events",
    "type": "User",
    "site_admin": False,
    "name": "Sushant",
    "company": None,
    "blog": "",
    "location": None,
    "email": None,
    "hireable": None,
    "bio": None,
    "twitter_username": "CurioSushi",
    "public_repos": 0,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2012-10-05T01:47:33Z",
    "updated_at": "2021-03-01T16:06:46Z",
    "private_gists": 0,
    "total_private_repos": 11,
    "owned_private_repos": 11,
    "disk_usage": 25002,
    "collaborators": 1,
    "two_factor_authentication": False,
    "plan": {
        "name": "free",
        "space": 976562499,
        "collaborators": 0,
        "private_repos": 10000,
    },
}
